
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

  java-backend:
    build:
      context: ./java-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./java-backend:/app
      - ./java-backend/src/main/resources/google-services.json:/app/src/main/resources/google-services.json
